name: lint

on: [push]

jobs:
  build:
    run-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: npm

      - name: Install project
        run: make install

      - name: Run linter
        run: make lint
